--  Criação das tabelas
CREATE TABLE CLUBS (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(80) NOT NULL,
    SURNAME VARCHAR(50),
    STATE CHAR(2) NOT NULL,
    CITY VARCHAR(100) NOT NULL,
    FOUNDED_AT DATE NOT NULL,
    STADIUM VARCHAR(50) NOT NULL,
    LOGO_PATH VARCHAR(300) NOT NULL
);

CREATE TABLE PLAYERS (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    COUNTRY VARCHAR(50) NOT NULL,
    BORN_AT DATE NOT NULL,
    DEBUT_AT DATE NOT NULL,
    SALARY DECIMAL(10,2) CHECK (SALARY >= 0),
    HEIGHT DECIMAL(5,2) CHECK (HEIGHT > 0),
    WEIGHT DECIMAL(5,2) CHECK (WEIGHT > 0),
    PHOTO_PATH VARCHAR(300),
    POSITION VARCHAR(20) NOT NULL,
    CLUB_ID BIGINT,
    FOREIGN KEY (CLUB_ID) REFERENCES CLUBS(ID)
);

CREATE TABLE COACHES (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(100) NOT NULL,
    COUNTRY VARCHAR(50) NOT NULL,
    BORN_AT DATE NOT NULL,
    DEBUT_AT DATE NOT NULL,
    SALARY DECIMAL(10,2) CHECK (SALARY >= 0),
    HEIGHT DECIMAL(5,2) CHECK (HEIGHT > 0),
    WEIGHT DECIMAL(5,2) CHECK (WEIGHT > 0),
    TACTICAL_STYLE VARCHAR(30) NOT NULL,
    TRAINING_METHODOLOGY VARCHAR(50) NOT NULL,
    PHOTO_PATH VARCHAR(300),
    CURRENT_CLUB_ID BIGINT,
    FOREIGN KEY (CURRENT_CLUB_ID) REFERENCES CLUBS(ID)
)