CREATE TABLE USERS (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(20) NOT NULL UNIQUE,
    EMAIL VARCHAR(20) NOT NULL UNIQUE,
    PASSWORD TEXT NOT NULL,
    ROLE VARCHAR(10) NOT NULL
)